# Generated by Django 2.2 on 2022-09-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.AppUser')),
            ],
        ),
    ]
