# Generated by Django 2.2 on 2022-09-02 01:29

import Message.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20220901_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=Message.models.get_default_user_id, on_delete=models.SET(Message.models.get_default_user), related_name='messages', to='appuser.AppUser'),
        ),
    ]
